#!/usr/bin/env python3
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parent
CREDENTIALS_PATH = PROJECT_DIR / "include" / "wifi_credentials.h"


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_credentials(path: Path, ssid: str, password: str, server_ip: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                "#pragma once",
                "",
                "// Generated by configure_esp32_wifi.py. This file is gitignored.",
                "#define DADN_WIFI_CANDIDATES { \\",
                f"  {{{c_string(ssid)}, {c_string(password)}}} \\",
                "}",
                "",
                f"#define DADN_SERVER_IP {c_string(server_ip)}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def upload_firmware(upload_port: str | None) -> int:
    command = [sys.executable, "-m", "platformio", "run", "--target", "upload"]
    if upload_port:
        command.extend(["--upload-port", upload_port])
    return subprocess.call(command, cwd=PROJECT_DIR)


def main() -> int:
    parser = argparse.ArgumentParser(description="Create local ESP32-CAM WiFi credentials and optionally upload firmware")
    parser.add_argument("--ssid", required=True, help="2.4 GHz WiFi SSID reachable by ESP32-CAM")
    parser.add_argument("--password", required=True, help="WiFi password")
    parser.add_argument("--server-ip", default="192.168.1.100", help="DADN/API server IP used by ESP32 health checks")
    parser.add_argument("--upload", action="store_true", help="Run PlatformIO upload after writing credentials")
    parser.add_argument("--upload-port", default=None, help="Upload serial port, e.g. COM13")
    args = parser.parse_args()

    write_credentials(CREDENTIALS_PATH, args.ssid, args.password, args.server_ip)
    print(f"[SUCCESS] Wrote local WiFi credentials: {CREDENTIALS_PATH}")
    print("[INFO] This file is gitignored and will not be committed.")

    if args.upload:
        return upload_firmware(args.upload_port)
    print("[INFO] Upload when ready:")
    print("       python -m platformio run --target upload")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
