#!/usr/bin/env python3
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from camera_profiles import frame_size_label, frame_size_macro, normalize_frame_size


PROJECT_DIR = Path(__file__).resolve().parent
CREDENTIALS_PATH = PROJECT_DIR / "include" / "wifi_credentials.h"


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_credentials(
    path: Path,
    ssid: str,
    password: str,
    server_ip: str,
    frame_size: str,
    *,
    vflip: bool,
    hmirror: bool,
    stream_timeout_ms: int,
    jpeg_quality: int,
    frame_delay_ms: int,
    enable_health_check: bool,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                "#pragma once",
                "",
                "// Generated by configure_esp32_wifi.py. This file is gitignored.",
                "#define DADN_WIFI_CANDIDATES { \\",
                f"  {{{c_string(ssid)}, {c_string(password)}}} \\",
                "}",
                "",
                f"#define DADN_SERVER_IP {c_string(server_ip)}",
                f"#define DADN_CAMERA_FRAME_SIZE {frame_size_macro(frame_size)}",
                f"#define DADN_ENABLE_SERVER_HEALTH_CHECK {1 if enable_health_check else 0}",
                f"#define DADN_CAMERA_VFLIP {1 if vflip else 0}",
                f"#define DADN_CAMERA_HMIRROR {1 if hmirror else 0}",
                f"#define DADN_STREAM_TIMEOUT_MS {stream_timeout_ms}",
                f"#define DADN_JPEG_QUALITY {jpeg_quality}",
                f"#define DADN_FRAME_DELAY_MS {frame_delay_ms}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def upload_firmware(upload_port: str | None) -> int:
    command = [sys.executable, "-m", "platformio", "run", "--target", "upload"]
    if upload_port:
        command.extend(["--upload-port", upload_port])
    return subprocess.call(command, cwd=PROJECT_DIR)


def main() -> int:
    parser = argparse.ArgumentParser(description="Create local ESP32-CAM WiFi credentials and optionally upload firmware")
    parser.add_argument("--ssid", required=True, help="2.4 GHz WiFi SSID reachable by ESP32-CAM")
    parser.add_argument("--password", required=True, help="WiFi password")
    parser.add_argument("--server-ip", default="192.168.1.100", help="DADN/API server IP used by ESP32 health checks")
    parser.add_argument(
        "--frame-size",
        default="QVGA",
        help="ESP32-CAM capture resolution. Supported: QVGA/VGA/SVGA/XGA/SXGA/UXGA or dimensions like 640x480",
    )
    parser.add_argument("--vflip", action="store_true", help="Flip camera vertically")
    parser.add_argument("--hmirror", action="store_true", help="Mirror camera horizontally")
    parser.add_argument("--stream-timeout-ms", type=int, default=300000, help="Stop each MJPEG client after N ms. 0 means no timeout.")
    parser.add_argument("--jpeg-quality", type=int, default=24, help="ESP32 camera JPEG quality. Higher is smaller/lower quality.")
    parser.add_argument("--frame-delay-ms", type=int, default=15, help="Delay between streamed frames. Lower reduces latency but increases WiFi/CPU load.")
    parser.add_argument("--enable-health-check", action="store_true", help="Ping DADN API server from ESP32 loop")
    parser.add_argument("--upload", action="store_true", help="Run PlatformIO upload after writing credentials")
    parser.add_argument("--upload-port", default=None, help="Upload serial port, e.g. COM13")
    args = parser.parse_args()

    try:
        frame_size = normalize_frame_size(args.frame_size)
    except ValueError as exc:
        parser.error(str(exc))

    write_credentials(
        CREDENTIALS_PATH,
        args.ssid,
        args.password,
        args.server_ip,
        frame_size,
        vflip=args.vflip,
        hmirror=args.hmirror,
        stream_timeout_ms=args.stream_timeout_ms,
        jpeg_quality=args.jpeg_quality,
        frame_delay_ms=args.frame_delay_ms,
        enable_health_check=args.enable_health_check,
    )
    print(f"[SUCCESS] Wrote local WiFi credentials: {CREDENTIALS_PATH}")
    print(f"[INFO] Camera capture frame size: {frame_size_label(frame_size)}")
    print("[INFO] This file is gitignored and will not be committed.")

    if args.upload:
        return upload_firmware(args.upload_port)
    print("[INFO] Upload when ready:")
    print("       python -m platformio run --target upload")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
