; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

; Tốc độ nạp code
upload_speed = 921600
; Tốc độ Serial Monitor
monitor_speed = 115200

; Uncomment if you want fixed COM port on your machine
; upload_port = COM7
; monitor_port = COM7

; Cấu hình quan trọng cho ESP32-CAM (để dùng được PSRAM cho AI)
build_flags =
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Thư viện cần thiết
lib_deps =
    esp32-camera